server:
  port: 8082
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_board?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: msa_user
    password: msa_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.example.board.domain
  configuration:
    map-underscore-to-camel-case: true
    
    
    
    
jwt:
  secret: my-super-secret-key-123456789012345
  expire-time-ms: 3600000    


#spring:
#  datasource:
#    url: jdbc:h2:mem:boarddb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  h2:
#    console:
#      enabled: true
